# Generated by Django 3.1.3 on 2021-03-26 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber_code', models.CharField(choices=[(88, 88), (90, 90), (91, 91), (93, 93), (94, 94), (95, 95), (98, 98), (99, 99)], default=91, max_length=2)),
                ('phonenumber', models.IntegerField(validators=[users.models.validate_number])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
