# Generated by Django 3.1.3 on 2021-03-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phonenumber_code',
            field=models.CharField(choices=[('88', 88), ('90', 90), ('91', 91), ('93', 93), ('94', 94), ('95', 95), ('98', 98), ('99', 99)], default=91, max_length=2),
        ),
    ]
