# Generated by Django 3.1.5 on 2021-03-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210326_1528'),
        ('users', '0002_auto_20210327_1455'),
    ]

    operations = [
    ]
