# Generated by Django 3.1.5 on 2021-03-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20210327_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phonenumber_code',
        ),
    ]
